import mongoose from 'mongoose';
const { Schema, model } = mongoose;
const testCase = new Schema({ input: String, expectedOutput: String, hidden: { type: Boolean, default: false } }, { _id: false });
export const User = model('User', new Schema({ name: { type: String, required: true }, email: { type: String, required: true, unique: true, lowercase: true }, password: { type: String, required: true }, role: { type: String, enum: ['user', 'admin'], default: 'user' } }, { timestamps: true }));
export const Problem = model('Problem', new Schema({ title: { type: String, required: true }, description: String, difficulty: { type: String, default: 'Easy' }, category: String, starterCode: String, language: { type: String, default: 'javascript' }, testCases: [testCase], expectedOutput: String, solutionExplanation: String }, { timestamps: true }));
export const Course = model('Course', new Schema({ title: String, description: String, technology: String, thumbnail: String, lessons: [{ title: String, youtubeUrl: String, order: Number, practiceProblemIds: [{ type: Schema.Types.ObjectId, ref: 'Problem' }] }], published: { type: Boolean, default: false } }, { timestamps: true }));
export const Assignment = model('Assignment', new Schema({ title: String, description: String, problems: [{ type: Schema.Types.ObjectId, ref: 'Problem' }], timeLimit: Number, published: { type: Boolean, default: false } }, { timestamps: true }));
export const Submission = model('Submission', new Schema({ userId: { type: Schema.Types.ObjectId, ref: 'User' }, problemId: { type: Schema.Types.ObjectId, ref: 'Problem' }, language: String, code: String, testResults: [Schema.Types.Mixed], passedTests: Number, totalTests: Number, score: Number, aiEvaluation: Schema.Types.Mixed }, { timestamps: true }));
export const Interview = model('Interview', new Schema({ userId: { type: Schema.Types.ObjectId, ref: 'User' }, type: String, questions: [String], answers: [{ question: String, answer: String }], score: Number, feedback: Schema.Types.Mixed, violations: { type: Number, default: 0 }, startedAt: { type: Date, default: Date.now }, completedAt: Date }, { timestamps: true }));
