import 'dotenv/config';
import express from 'express'; import cors from 'cors'; import mongoose from 'mongoose'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken';
import { User, Course, Problem, Assignment, Submission, Interview } from './models.js'; import { auth, admin } from './middleware/auth.js'; import { execute } from './services/codeExecutionService.js'; import { questions, evaluateInterview, evaluateCode } from './services/aiService.js';
const app = express(); app.use(cors()); app.use(express.json({ limit: '200kb' }));
const ok = (res, data, status = 200) => res.status(status).json({ success: true, data }); const fail = (res, message, status = 400) => res.status(status).json({ success: false, message }); const token = u => jwt.sign({ id: u._id }, process.env.JWT_SECRET, { expiresIn: '7d' });
app.get('/api/health', (_, res) => ok(res, { status: 'ok', database: mongoose.connection.readyState === 1 ? 'connected' : 'disconnected' }));
app.get('/api/config', (_, res) => ok(res, { maxViolations: Math.max(1, Number(process.env.MAX_VIOLATIONS) || 3), executionMode: process.env.CODE_EXECUTION_MODE === 'piston' ? 'external' : 'mock' }));
app.post('/api/auth/register', async (req,res) => { try { const { name, email, password }=req.body; if (!name || !email || !password || password.length < 8) return fail(res,'Name, email, and an 8-character password are required.'); if(await User.exists({email:email.toLowerCase()})) return fail(res,'Email is already registered.',409); const user=await User.create({name,email,password:await bcrypt.hash(password,12)}); ok(res,{token:token(user),user:{id:user.id,name:user.name,email:user.email,role:user.role}},201); } catch { fail(res,'Could not register account.'); } });
app.post('/api/auth/login', async (req,res) => { const user=await User.findOne({email:req.body.email?.toLowerCase()}); if(!user || !await bcrypt.compare(req.body.password||'',user.password)) return fail(res,'Invalid email or password.',401); ok(res,{token:token(user),user:{id:user.id,name:user.name,email:user.email,role:user.role}}); }); app.get('/api/auth/me',auth,(req,res)=>ok(res,req.user));
app.get('/api/courses',auth,async (_,res)=>ok(res,await Course.find({published:true}).select('-lessons.practiceProblemIds'))); app.get('/api/courses/:id',auth,async(req,res)=>{const x=await Course.findById(req.params.id).populate('lessons.practiceProblemIds','title difficulty'); x?ok(res,x):fail(res,'Course not found.',404)});
app.get('/api/problems',auth,async(_,res)=>ok(res,await Problem.find().select('-testCases.expectedOutput'))); app.get('/api/problems/:id',auth,async(req,res)=>{const x=await Problem.findById(req.params.id).select('-testCases.expectedOutput');x?ok(res,x):fail(res,'Problem not found.',404)});
app.get('/api/assignments',auth,async(_,res)=>ok(res,await Assignment.find({published:true}).populate('problems','title difficulty category'))); app.get('/api/assignments/:id',auth,async(req,res)=>{const x=await Assignment.findById(req.params.id).populate('problems');x?ok(res,x):fail(res,'Assignment not found.',404)});
async function testSubmission(req,res,store) { const { problemId, language='javascript', code='' }=req.body; if(!problemId||!code.trim()) return fail(res,'Problem and code are required.'); const problem=await Problem.findById(problemId); if(!problem) return fail(res,'Problem not found.',404); const cases=store?problem.testCases:problem.testCases.filter(t=>!t.hidden); const results=[]; for(const test of cases) { const run=await execute({language,source_code:code,stdin:test.input}); const passed=run.status === 'mock' ? false : run.status === 'accepted' && run.stdout.trim()===test.expectedOutput.trim(); results.push({input:test.input,expectedOutput:test.hidden&&store?undefined:test.expectedOutput,stdout:run.stdout,stderr:run.stderr,status:run.status,passed}); } const passedTests=results.filter(r=>r.passed).length, score=cases.length?Math.round(passedTests/cases.length*100):0; if(!store)return ok(res,{results,passedTests,totalTests:cases.length,score,mock:results.some(r=>r.status==='mock')}); const aiEvaluation=await evaluateCode(problem,code,results); const submission=await Submission.create({userId:req.user._id,problemId,language,code,testResults:results,passedTests,totalTests:cases.length,score,aiEvaluation}); ok(res,submission,201); }
app.post('/api/submissions/run',auth,(req,res)=>testSubmission(req,res,false)); app.post('/api/submissions',auth,(req,res)=>testSubmission(req,res,true)); app.post('/api/submissions/:id/evaluate',auth,async(req,res)=>{const s=await Submission.findOne({_id:req.params.id,userId:req.user._id});if(!s)return fail(res,'Submission not found.',404);ok(res,s.aiEvaluation)}); app.get('/api/submissions/recent',auth,async(req,res)=>ok(res,await Submission.find({userId:req.user._id}).populate('problemId','title').sort('-createdAt').limit(5)));
app.post('/api/interviews',auth,async(req,res)=>{const allowed=['MERN Stack','JavaScript','DSA','Frontend','Backend']; const type=allowed.includes(req.body.type)?req.body.type:'JavaScript', generated=await questions(type); const interview=await Interview.create({userId:req.user._id,type,questions:generated.questions});ok(res,{interview,aiAvailable:generated.aiAvailable},201)}); app.get('/api/interviews/:id',auth,async(req,res)=>{const x=await Interview.findOne({_id:req.params.id,userId:req.user._id});x?ok(res,x):fail(res,'Interview not found.',404)}); app.post('/api/interviews/:id/complete',auth,async(req,res)=>{const i=await Interview.findOne({_id:req.params.id,userId:req.user._id});if(!i)return fail(res,'Interview not found.',404);if(i.completedAt)return fail(res,'This interview has already been completed.',409);if(!Array.isArray(req.body.answers)||req.body.answers.length!==5||req.body.answers.some(a=>!String(a.answer||'').trim()))return fail(res,'Five non-empty answers are required.'); i.answers=req.body.answers.map((a,index)=>({question:i.questions[index],answer:String(a.answer).trim().slice(0,10000)}));i.violations=Math.max(0,Number(req.body.violations)||0);i.feedback=await evaluateInterview(i.type,i.answers);i.score=i.feedback.score;i.completedAt=new Date();await i.save();ok(res,i)}); app.get('/api/interviews/recent',auth,async(req,res)=>ok(res,await Interview.find({userId:req.user._id,completedAt:{$ne:null}}).sort('-completedAt').limit(1)));
app.get('/api/admin/users',auth,admin,async(_,res)=>ok(res,await User.find().select('name email role createdAt')));
for (const [key, Model] of Object.entries({courses:Course,problems:Problem,assignments:Assignment})) { app.get(`/api/admin/${key}`,auth,admin,async(_,res)=>ok(res,await Model.find())); app.post(`/api/admin/${key}`,auth,admin,async(req,res)=>ok(res,await Model.create(req.body),201)); app.put(`/api/admin/${key}/:id`,auth,admin,async(req,res)=>ok(res,await Model.findByIdAndUpdate(req.params.id,req.body,{new:true}))); app.delete(`/api/admin/${key}/:id`,auth,admin,async(req,res)=>{await Model.findByIdAndDelete(req.params.id);ok(res,{id:req.params.id})}); }
app.use((err,req,res,next)=>{console.error(err);fail(res,'Unexpected server error.',500)}); const port=process.env.PORT||5000; mongoose.connect(process.env.MONGODB_URI||'mongodb://127.0.0.1:27017/mern-interview-platform').then(()=>app.listen(port,()=>console.log(`API listening on ${port}`))).catch(e=>{console.error('MongoDB connection failed:',e.message);process.exit(1)});
